### ISSUE TITLE
Module build failed at ng2-slimscroll/index.ts

### ISSUE THREAD

**Issue by MorlaRamakrishna** [jkuri/ng2-slimscroll#49]
I have followed below steps

**1. Installation**
          _npm install ng2-slimscroll_
**2. Imported module like**
          _import { SlimScrollModule } from 'ng2-slimscroll';_
          _imports: [       ....................
                          SlimScrollModule,
                                ......................]_

Error out in **nodemodules/ng2-slimscroll/index.ts** like
 
ERROR in ./~/ng2-slimscroll/index.ts
Module build failed: Error
    at new FatalError (E:\ReconWorkspace\AgreeGateway\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (E:\ReconWorkspace\AgreeGateway\node_modules\tslint\lib\configurat
ion.js:47:15)
    at resolveOptions (E:\ReconWorkspace\AgreeGateway\node_modules\tslint-loader\index.js:35:64)
    at Object.module.exports (E:\ReconWorkspace\AgreeGateway\node_modules\tslint-loader\index.js:124
:17)
 @ ./src/main/webapp/app/test/test.module.ts 21:23-48
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
 @ multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/
app/app.main

**Comment by Senthe** [comment]
I have the same issue but with completely different package. I think it's a webpack/tslint bug.

**Comment by shancox** [comment]
replace:
import { SlimScrollModule } from 'ngx-slimscroll';

to
import { NgSlimScrollModule } from 'ngx-slimscroll';
